### PR TITLE
initial release

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by aptalca** [comment]
~~Don't merge yet. I got the branch wrong~~
fixed

**Review by thelamer — APPROVED** [review]
Damn Alpine needs to get 3.0 built

**Comment by thelamer** [comment]
I honestly bet you could just bump pkgver here https://git.alpinelinux.org/aports/tree/community/audacity/APKBUILD
I don't see new deps, you ever use abuild and alpine-sdk @aptalca ?

**Comment by aptalca** [comment]
Yeah, I was going to submit a PR for it on alpine. I did submit a few before so I'm familiar with their build tools.

**Comment by aptalca** [comment]
@thelamer scratch that. 3.0.0 requires a custom wxgtk3 and I have no clue how to use that in alpine's build system.

Got a nice little build error with just the pkgver change :-)
```
CMake Error at cmake-proxies/wxWidgets/CMakeLists.txt:242 (message):
  

  ########################################################################

  Audacity version 3.0.0 or higher requires use of a customized version of
  wxWidgets.  For details:

    https://wiki.audacityteam.org/wiki/Building_for_Distros

  ########################################################################



-- Configuring incomplete, errors occurred!
```

**Review by Roxedus — APPROVED** [review]

**Pull request merged**
